- name: Configure Pihole a Proxmox VM
  hosts: all
  become: true
  tasks:
    - name:  Makes sure Curl is install
      pacman:
        name: curl
        state: present

    - name: Install Pihole on the command line
      shell: curl -sSL https://install.pi-hole.net | bash




